<HTML><HEAD><TITLE>IPI00019148 - IGBP1 Immunoglobulin-binding protein 1 ENSG00000089289 - Detailed Information</TITLE><style>
a:hover{color:red; text-decoration:underline;}
</style></HEAD><BODY link=696969 vlink=696969>
<A NAME=top></A><FONT FACE="Arial, Helvetica">
<B>Description</B>: <A HREF=http://srs.ebi.ac.uk/srsbin/cgi-bin/wgetz?-e+[IPI-acc:IPI00019148]+-vn+2>IPI00019148</A> - <B>IGBP1 Immunoglobulin-binding protein 1 </B> - <A HREF=http://www.ensembl.org/Homo_sapiens/geneview?gene=ENSG00000089289>ENSG00000089289</A><P>
<TABLE BORDER=1>
<TR><TD><FONT FACE="Arial, Helvetica">Protein size:</TD><TD ALIGN=RIGHT><FONT FACE="Arial, Helvetica">339 amino acids (39.2kDa)</TD></TR>
<TR><TD><FONT FACE="Arial, Helvetica">No. samples:</TD><TD ALIGN=RIGHT><FONT FACE="Arial, Helvetica">3 replicates, 22 bands</TD></TR>
<TR><TD><FONT FACE="Arial, Helvetica">Total <A HREF=#bands>sequence-coverage</A>:</TD><TD ALIGN=RIGHT><FONT FACE="Arial, Helvetica">40.7%</TD></TR>
<TR><TD><FONT FACE="Arial, Helvetica">Total <A HREF=#sc>spectral-counts</A>:</TD><TD ALIGN=RIGHT><FONT FACE="Arial, Helvetica">23</TD></TR>
</TABLE><P><TD ALIGN=RIGHT><FONT FACE="Arial, Helvetica">[ <A HREF="http://www.scripps.edu/cgi-bin/cravatt/pmap3x.pl?size=300&searchterm=IPI00019148">Time-course</A> ]</TD><P><HR><TABLE BORDER=0><TR><TD><IMG SRC=/cravatt/mwmarker.png><IMG SRC=/cgi-bin/cravatt/pg-maker.pl?dset=/web/docs/cravatt/protomap/pmap2_data/MFPCM_vs_MFPSOL.pmap&hitid=1736&numbands=22&n=3&output=png&linepos=&gradcolor=&altcolor=></TD></TR></TABLE><P>
<HR><B>Conserved domains:</B> (click image for details)<BR>
<FORM ID="id_frm_newsearch" NAME="newsrch" ACTION="http://www.ncbi.nlm.nih.gov/Structure/cdd/wrpsb.cgi" METHOD="post" TARGET="_blank">
<INPUT TYPE="hidden" name="seqinput" value="MAAEDELQLPRLPELFETGRQLLDEVEVATEPAGSRIVQEKVFKGLDLLEKAAEMLSQLDLFSRNEDLEEIASTDLKYLLVPAFQGALTMKQVNPSKRLDHLQRAREHFINYLTQCHCYHVAEFELPKTMNNSAENHTANSSMAYPSLVAMASQRQAKIQRYKQKKELEHRLSAMKSAVESGQADDERVREYYLLHLQRWIDISLEEIESIDQEIKILRERDSSREASTSNSSRQERPPVKPFILTRNMAQAKVFGAGYPSLPTMTVSDWYEQHRKYGALPDQGIAKAAPEEFRKAAQQQEEQEEKEEEDDEQTLHRAREWDDWKDTHPRGYGNRQNMG">
<INPUT TYPE="image" SRC="http://www.ncbi.nlm.nih.gov/Structure/cdd/wrpsb.cgi?JUSTPIC&seqinput=MAAEDELQLPRLPELFETGRQLLDEVEVATEPAGSRIVQEKVFKGLDLLEKAAEMLSQLDLFSRNEDLEEIASTDLKYLLVPAFQGALTMKQVNPSKRLDHLQRAREHFINYLTQCHCYHVAEFELPKTMNNSAENHTANSSMAYPSLVAMASQRQAKIQRYKQKKELEHRLSAMKSAVESGQADDERVREYYLLHLQRWIDISLEEIESIDQEIKILRERDSSREASTSNSSRQERPPVKPFILTRNMAQAKVFGAGYPSLPTMTVSDWYEQHRKYGALPDQGIAKAAPEEFRKAAQQQEEQEEKEEEDDEQTLHRAREWDDWKDTHPRGYGNRQNMG" BORDER=1></FORM>
<FORM METHOD="POST" ACTION="http://www.expasy.org/cgi-bin/protscale.pl?1">
<INPUT TYPE="hidden" name="sequence" VALUE="MAAEDELQLPRLPELFETGRQLLDEVEVATEPAGSRIVQEKVFKGLDLLEKAAEMLSQLDLFSRNEDLEEIASTDLKYLLVPAFQGALTMKQVNPSKRLDHLQRAREHFINYLTQCHCYHVAEFELPKTMNNSAENHTANSSMAYPSLVAMASQRQAKIQRYKQKKELEHRLSAMKSAVESGQADDERVREYYLLHLQRWIDISLEEIESIDQEIKILRERDSSREASTSNSSRQERPPVKPFILTRNMAQAKVFGAGYPSLPTMTVSDWYEQHRKYGALPDQGIAKAAPEEFRKAAQQQEEQEEKEEEDDEQTLHRAREWDDWKDTHPRGYGNRQNMG">
<INPUT TYPE="hidden" name="scale" VALUE="Hphob. / Kyte & Doolittle">
<INPUT TYPE="hidden" name="window" VALUE="9">
<INPUT TYPE="hidden" name="weight_edges" VALUE="100">
<INPUT TYPE="hidden" name="weight_var" VALUE="linear">
<INPUT TYPE="hidden" name="norm" VALUE="no">
<INPUT TYPE="submit" VALUE="Hydropathy plot">
</FORM>
<HR>
<A NAME=bands></A><P><FONT FACE="Courier New">
<A HREF=#band1>Band1</A> <A HREF=#band2>Band2</A> <A HREF=#band3>Band3</A> <A HREF=#band4>Band4</A> <A HREF=#band5>Band5</A> <A HREF=#band6>Band6</A> <A HREF=#band7>Band7</A> <A HREF=#band8>Band8</A> <A HREF=#band9>Band9</A> <A HREF=#band10>Band10</A> <A HREF=#band11>Band11</A> <A HREF=#band12>Band12</A> <A HREF=#band13>Band13</A> <A HREF=#band14>Band14</A> <A HREF=#band15>Band15</A> <A HREF=#band16>Band16</A> <A HREF=#band17>Band17</A> <A HREF=#band18>Band18</A> <A HREF=#band19>Band19</A> <A HREF=#band20>Band20</A> <A HREF=#band21>Band21</A> <A HREF=#band22>Band22</A> <A NAME=top></A><FONT FACE="Courier New">
<HR><A NAME=band1></A><H3><FONT FACE="Courier New">Band #1</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band2></A><H3><FONT FACE="Courier New">Band #2</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band3></A><H3><FONT FACE="Courier New">Band #3</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band4></A><H3><FONT FACE="Courier New">Band #4</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band5></A><H3><FONT FACE="Courier New">Band #5</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band6></A><H3><FONT FACE="Courier New">Band #6</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band7></A><H3><FONT FACE="Courier New">Band #7</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band8></A><H3><FONT FACE="Courier New">Band #8</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band9></A><H3><FONT FACE="Courier New">Band #9</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band10></A><H3><FONT FACE="Courier New">Band #10</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band11></A><H3><FONT FACE="Courier New">Band #11</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band12></A><H3><FONT FACE="Courier New">Band #12</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP R</font><font face="Courier New" color=cc00cc>LPELFETGR QLLDEVEVAT EPAGSR</font><font face="Courier New" color=000000>IVQE KVFKGLDLLE K</font><font face="Courier New" color=cc00cc>AAEMLSQLD LFSR</font><font face="Courier New" color=0000ff>NEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM K</font><font face="Courier New" color=000000>QVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR</font><font face="Courier New" color=0000ff> EYYLLHLQRW IDISLEEIES IDQEIK</font><font face="Courier New" color=000000>ILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHR</font><font face="Courier New" color=0000ff>KYGAL PDQGIAK</font><font face="Courier New" color=000000>AAP EEFRK</font><font face="Courier New" color=cc00cc>AAQQQ EEQEEKEEED DEQTLHR</font><font face="Courier New" color=0000ff>ARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR</font><font face="Courier New" color=000000> GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 40.7%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band13></A><H3><FONT FACE="Courier New">Band #13</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band14></A><H3><FONT FACE="Courier New">Band #14</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band15></A><H3><FONT FACE="Courier New">Band #15</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band16></A><H3><FONT FACE="Courier New">Band #16</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band17></A><H3><FONT FACE="Courier New">Band #17</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band18></A><H3><FONT FACE="Courier New">Band #18</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band19></A><H3><FONT FACE="Courier New">Band #19</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band20></A><H3><FONT FACE="Courier New">Band #20</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band21></A><H3><FONT FACE="Courier New">Band #21</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=band22></A><H3><FONT FACE="Courier New">Band #22</H3><TABLE border=0 WIDTH=1000><TR><TD>
<FONT FACE="Courier New"><BR>
</B>&nbsp&nbsp&nbsp&nbsp&nbsp 1&nbsp <B> MAAEDELQLP RLPELFETGR QLLDEVEVAT EPAGSRIVQE KVFKGLDLLE KAAEMLSQLD LFSRNEDLEE IASTDLKYLL<BR>
</B>&nbsp&nbsp&nbsp&nbsp 81&nbsp <B> VPAFQGALTM KQVNPSKRLD HLQRAREHFI NYLTQCHCYH VAEFELPKTM NNSAENHTAN SSMAYPSLVA MASQRQAKIQ<BR>
</B>&nbsp&nbsp&nbsp 161&nbsp <B> RYKQKKELEH RLSAMKSAVE SGQADDERVR EYYLLHLQRW IDISLEEIES IDQEIKILRE RDSSREASTS NSSRQERPPV<BR>
</B>&nbsp&nbsp&nbsp 241&nbsp <B> KPFILTRNMA QAKVFGAGYP SLPTMTVSDW YEQHRKYGAL PDQGIAKAAP EEFRKAAQQQ EEQEEKEEED DEQTLHRARE<BR>
</B>&nbsp&nbsp&nbsp 321&nbsp <B> WDDWKDTHPR GYGNRQNMG</TD></TR></TABLE>

<P>Sequence coverage: 0%<BR>
<A HREF=#top>Back to top</A>
<HR><A NAME=sc></A><B>Spectral counts per band</B>:<P>
<TABLE BORDER=1><FONT FACE="Courier New">
<TR><TD></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Secreted 231MFP</FONT></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Secreted 231MFP</FONT></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Secreted 231MFP</FONT></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Soluble 231MFP</FONT></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Soluble 231MFP</FONT></TD>
<TD ALIGN=CENTER><FONT SIZE=-1>Soluble 231MFP</FONT></TD>
<TD ALIGN=CENTER>Secreted 231MFP<BR><B>Average</B></TD><TD ALIGN=CENTER>Soluble 231MFP<BR><B>Average</B></TD><TD ALIGN=CENTER>Secreted 231MFP<BR><B>Sum</B></TD><TD ALIGN=CENTER>Soluble 231MFP<BR><B>Sum</B></TD></TR>
<TR><TD>Band1</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band2</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band3</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band4</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band5</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band6</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band7</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band8</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band9</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band10</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band11</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band12</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>4</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>1</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>7</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>4</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>7</B></TD>
<TD ALIGN=CENTER>1.6</TD><TD ALIGN=CENTER>6</TD><TD ALIGN=CENTER>5</TD><TD ALIGN=CENTER>18</TD></TR>
<TR><TD>Band13</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band14</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band15</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band16</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band17</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band18</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band19</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band20</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band21</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
<TR><TD>Band22</TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=B44444><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER BGCOLOR=87CEFA><B>-</B></TD>
<TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD><TD ALIGN=CENTER>-</TD></TR>
</TABLE>
<P>Total Spectral Counts: 23<BR>
<TABLE BORDER=1>
<TR>
	<TD ALIGN=CENTER><B>Sample</B></TD>
	<TD ALIGN=CENTER><B>Sum</B></TD>
	<TD ALIGN=CENTER><B>Average</B></TD>
	<TD ALIGN=CENTER><B>Std. Dev</B></TD>
</TR>
<TR>
	<TD>Secreted 231MFP</TD>
	<TD ALIGN=CENTER>5</TD>
	<TD ALIGN=CENTER>1.6</TD>
<TD ALIGN=CENTER>1.6</TD>
</TR>
<TR>
	<TD>Soluble 231MFP</TD>
	<TD ALIGN=CENTER>18</TD>
	<TD ALIGN=CENTER>6</TD>
	<TD ALIGN=CENTER>1.4</TD>
</TR>
</TABLE>
p-value: 0.050248<BR>
